/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include"rpc.h"
#include<rpc/rpc.h>
#include<stdio.h>
#include<stdlib.h>
#include<sys/types.h>
#include<netinet/in.h>
#include<netdb.h>
#include<string.h>

main(argc, argv)
int argc;
char *argv[];
{
	
	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
    
    //Variable declariation
    CLIENT *clnt;
    char  *result_1;
	char  rpc_process_1_arg;
	char*input=malloc(sizeof(char)*BUFSIZ);
    
    //creat client
	clnt = clnt_create(argv[1], RPCPROG, RPCVERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1);
	}
    
    //receive user input and call RPC
	while(1){
        //1.get user input
        bzero(input,sizeof(input));
        printf("Enter(input'quit'to stop):");
        fgets(input,BUFSIZ,stdin);
        
        //2.check for exit
        if(strcmp(input,"QUIT")==0){
            break;
        }
        
        //3.call RPC with passing parameter
        if(strstr(input,"C00L")){
            rpc_process_1(input, clnt);
	        /*if (result_1 == NULL) {
		    clnt_perror(clnt, "call failed:");
	        }else{
                printf(result_1);
            }*/
        }
        
    }
}











